typo: corrected module name to SocketServer
'sockerserver' fails on systems without Python3:
# python example_server.py
Traceback (most recent call last):
  File "example_server.py", line 1, in <module>
    import socketserver
ImportError: No module named socketserver
//note
"socketserver doesn't exists(sic) in Python 2.7. In Python 2.7 it is called SocketServer" 
//source: https://github.com/AdvancedClimateSystems/uModbus/issues/83
//see also: https://pymotw.com/2/SocketServer/
#swipswaps